-- ============================================================================
-- SEED DATA - DATOS FICTICIOS PARA TESTING
-- ============================================================================
-- IMPORTANTE: Este archivo NO debe subirse a GitHub
-- Contraseñas de todos los usuarios: testpass123
-- Los slot_id se resuelven con subqueries para evitar IDs hardcodeados
-- ============================================================================

-- ============================================================================
-- 1. INSERTAR USUARIOS FICTICIOS (47 usuarios)
-- ============================================================================

INSERT INTO users (username, password_hash, role, created_at) VALUES
('Luis',    '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'admin', NOW()),
('Jorge',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'admin', NOW()),
('Ash',     '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '30 days'),
('Misty',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '25 days'),
('Brock',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '20 days'),
('Cynthia', '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '18 days'),
('Blaine',  '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '15 days'),
('Sabrina', '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '12 days'),
('Giovanni','$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '10 days'),
('Jessie',  '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '8 days'),
('James',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '6 days'),
('Meowth',  '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '5 days'),
('Whitney', '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '4 days'),
('Erika',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '3 days'),
('Surge',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '2 days'),
('Koga',    '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '1 day'),
('Janine',  '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW()),
('Lorelei', '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '29 days'),
('Bruno',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '24 days'),
('Agatha',  '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '19 days'),
('Lance',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '14 days'),
('Blue',    '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '11 days'),
('Green',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '9 days'),
('Red',     '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '7 days'),
('Yellow',  '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '4 days'),
('Leaf',    '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '2 days'),
('Oak',     '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '1 day'),
('Ariana',  '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '28 days'),
('Atticus', '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '27 days'),
('Bianca',  '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '26 days'),
('Brendan', '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '23 days'),
('Clair',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '22 days'),
('Dahlia',  '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '21 days'),
('Delia',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '17 days'),
('Erreka',  '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '16 days'),
('Flora',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '13 days'),
('Fuchsia', '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '10 days'),
('Giselle', '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '8 days'),
('Grant',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '7 days'),
('Harlene', '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '6 days'),
('Iris',    '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '5 days'),
('Irina',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '4 days'),
('Jackie',  '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '3 days'),
('Jasmine', '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '2 days'),
('Juan',    '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '1 day'),
('Kaida',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW()),
('Klara',   '$2b$10$V8nb0ZLMZIbPeKTnOIyav.UdLwSYvjh4Z0lVpNQYUe2yI/TFOXff6', 'user', NOW() - INTERVAL '12 days');

-- ============================================================================
-- 2. INSERTAR SLOTS (subquery por username para evitar IDs hardcodeados)
-- ============================================================================

INSERT INTO game_slots (user_id, slot_number, explorer, explorer_name, color, difficulty_id, sticker, hp, pokeball, position_r, position_c, is_game_over, is_goal, updated_at)
SELECT u.id, s.slot_number, s.explorer, s.explorer_name, s.color, s.difficulty_id, s.sticker, s.hp, s.pokeball, s.position_r, s.position_c, s.is_game_over, s.is_goal, s.updated_at
FROM users u
JOIN (VALUES
  ('Luis',    1,'boy', 'Luis',    '#FFD700','normal',  '/img/stickers/pikachu.webp',10,25,0,0,false,false,NOW()),
  ('Luis',    2,'boy', 'Luis',    '#FFD700','dificil',  '/img/stickers/charizard.webp',8,20,3,3,false,false,NOW()-INTERVAL'2 days'),
  ('Luis',    3,'boy', 'Luis',    '#FFD700','facil',   '/img/stickers/blastoise.webp',10,30,0,0,false,true, NOW()-INTERVAL'1 day'),
  ('Jorge',   1,'boy', 'Jorge',   '#FF6347','normal',  '/img/stickers/venusaur.webp',10,25,0,0,false,false,NOW()),
  ('Jorge',   2,'boy', 'Jorge',   '#FF6347','infernal', '/img/stickers/dragonite.webp',5,15,5,5,true, false,NOW()-INTERVAL'2 days'),
  ('Jorge',   3,'boy', 'Jorge',   '#FF6347','dificil',  '/img/stickers/gyarados.webp',9,22,2,2,false,false,NOW()-INTERVAL'1 day'),
  ('Ash',     1,'boy', 'Ash',     '#019273','normal',   '/img/stickers/pikachu.webp',7,18,4,3,false,false,NOW()),
  ('Ash',     2,'boy', 'Ash',     '#019273','dificil',  '/img/stickers/articuno.webp',4,10,2,1,true, false,NOW()-INTERVAL'3 days'),
  ('Ash',     3,'boy', 'Ash',     '#019273','facil',   '/img/stickers/meowth.webp',10,25,0,0,false,true, NOW()-INTERVAL'1 day'),
  ('Misty',   1,'girl','Misty',   '#00CED1','normal',   '/img/stickers/lapras.webp',8,20,3,4,false,false,NOW()),
  ('Misty',   2,'girl','Misty',   '#00CED1','dificil',  '/img/stickers/psyduck.webp',6,14,1,2,false,false,NOW()-INTERVAL'2 days'),
  ('Misty',   3,'girl','Misty',   '#00CED1','infernal', '/img/stickers/chansey.webp',3, 8,4,4,true, false,NOW()-INTERVAL'1 day'),
  ('Brock',   1,'boy', 'Brock',   '#A0826D','normal',   '/img/stickers/cubone.webp',9,22,2,3,false,false,NOW()),
  ('Brock',   2,'boy', 'Brock',   '#A0826D','facil',   '/img/stickers/grimer.webp',10,28,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Brock',   3,'boy', 'Brock',   '#A0826D','dificil',  '/img/stickers/bulbasaur.webp',7,16,5,2,false,false,NOW()-INTERVAL'1 day'),
  ('Cynthia', 1,'girl','Cynthia', '#8B4789','dificil',  '/img/stickers/mewtwo.webp',8,21,3,3,false,false,NOW()),
  ('Cynthia', 2,'girl','Cynthia', '#8B4789','normal',  '/img/stickers/gengar.webp',10,26,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Cynthia', 3,'girl','Cynthia', '#8B4789','infernal', '/img/stickers/mew.webp',6,12,4,5,true, false,NOW()-INTERVAL'1 day'),
  ('Blaine',  1,'boy', 'Blaine',  '#FF4500','dificil',  '/img/stickers/magmar.webp',7,17,4,2,false,false,NOW()),
  ('Blaine',  2,'boy', 'Blaine',  '#FF4500','infernal', '/img/stickers/charmander.webp',5,11,2,1,true, false,NOW()-INTERVAL'2 days'),
  ('Blaine',  3,'boy', 'Blaine',  '#FF4500','normal',   '/img/stickers/charizard.webp',9,23,1,3,false,false,NOW()-INTERVAL'1 day'),
  ('Sabrina', 1,'girl','Sabrina', '#9932CC','normal',   '/img/stickers/jynx.webp',8,19,3,2,false,false,NOW()),
  ('Sabrina', 2,'girl','Sabrina', '#9932CC','dificil',  '/img/stickers/kadabra.webp',7,15,2,4,false,false,NOW()-INTERVAL'2 days'),
  ('Sabrina', 3,'girl','Sabrina', '#9932CC','facil',   '/img/stickers/clefairy.webp',10,27,0,0,false,true, NOW()-INTERVAL'1 day'),
  ('Giovanni',1,'boy', 'Giovanni','#1C1C1C','normal',   '/img/stickers/ditto.webp',9,21,2,3,false,false,NOW()),
  ('Giovanni',2,'boy', 'Giovanni','#1C1C1C','infernal', '/img/stickers/snorlax.webp',4, 9,5,4,true, false,NOW()-INTERVAL'2 days'),
  ('Giovanni',3,'boy', 'Giovanni','#1C1C1C','dificil',  '/img/stickers/nidoqueen.webp',8,20,3,1,false,false,NOW()-INTERVAL'1 day'),
  ('Jessie',  1,'girl','Jessie',  '#FF1493','normal',   '/img/stickers/pidgeotto.webp',7,16,4,3,false,false,NOW()),
  ('Jessie',  2,'girl','Jessie',  '#FF1493','facil',   '/img/stickers/ivysaur.webp',10,26,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Jessie',  3,'girl','Jessie',  '#FF1493','dificil',  '/img/stickers/gloom.webp',6,13,3,2,false,false,NOW()-INTERVAL'1 day'),
  ('James',   1,'boy', 'James',   '#4169E1','normal',   '/img/stickers/squirtle.webp',8,20,3,3,false,false,NOW()),
  ('James',   2,'boy', 'James',   '#4169E1','dificil',  '/img/stickers/tentacool.webp',7,17,2,2,false,false,NOW()-INTERVAL'2 days'),
  ('James',   3,'boy', 'James',   '#4169E1','facil',   '/img/stickers/krabby.webp',10,29,0,0,false,true, NOW()-INTERVAL'1 day'),
  ('Meowth',  1,'boy', 'Meowth',  '#FFD700','normal',   '/img/stickers/meowth.webp',9,22,2,4,false,false,NOW()),
  ('Meowth',  2,'boy', 'Meowth',  '#FFD700','infernal', '/img/stickers/persian.webp',5,10,4,4,true, false,NOW()-INTERVAL'2 days'),
  ('Meowth',  3,'boy', 'Meowth',  '#FFD700','facil',   '/img/stickers/pikachu.webp',10,25,0,0,false,true, NOW()-INTERVAL'1 day'),
  ('Whitney', 1,'girl','Whitney', '#FF69B4','normal',   '/img/stickers/miltank.webp',8,19,3,2,false,false,NOW()),
  ('Whitney', 2,'girl','Whitney', '#FF69B4','facil',   '/img/stickers/clefable.webp',10,28,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Whitney', 3,'girl','Whitney', '#FF69B4','dificil',  '/img/stickers/wigglytuff.webp',6,14,4,3,false,false,NOW()-INTERVAL'1 day'),
  ('Erika',   1,'girl','Erika',   '#00AA00','normal',   '/img/stickers/vileplume.webp',9,21,2,3,false,false,NOW()),
  ('Erika',   2,'girl','Erika',   '#00AA00','dificil',  '/img/stickers/bellossom.webp',7,16,3,1,false,false,NOW()-INTERVAL'2 days'),
  ('Erika',   3,'girl','Erika',   '#00AA00','infernal', '/img/stickers/oddish.webp',4, 8,5,5,true, false,NOW()-INTERVAL'1 day'),
  ('Surge',   1,'boy', 'Surge',   '#FFB90F','dificil',  '/img/stickers/raichu.webp',8,20,3,3,false,false,NOW()),
  ('Surge',   2,'boy', 'Surge',   '#FFB90F','normal',   '/img/stickers/pikachu.webp',9,23,1,2,false,false,NOW()-INTERVAL'2 days'),
  ('Surge',   3,'boy', 'Surge',   '#FFB90F','facil',   '/img/stickers/magneton.webp',10,30,0,0,false,true, NOW()-INTERVAL'1 day'),
  ('Koga',    1,'boy', 'Koga',    '#8B008B','normal',   '/img/stickers/weezing.webp',7,17,4,2,false,false,NOW()),
  ('Koga',    2,'boy', 'Koga',    '#8B008B','infernal', '/img/stickers/muk.webp',5,11,2,3,true, false,NOW()-INTERVAL'2 days'),
  ('Koga',    3,'boy', 'Koga',    '#8B008B','dificil',  '/img/stickers/golbat.webp',8,19,3,4,false,false,NOW()-INTERVAL'1 day'),
  ('Janine',  1,'girl','Janine',  '#9932CC','normal',   '/img/stickers/ariados.webp',8,20,3,2,false,false,NOW()),
  ('Janine',  2,'girl','Janine',  '#9932CC','facil',   '/img/stickers/spinarak.webp',10,27,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Janine',  3,'girl','Janine',  '#9932CC','dificil',  '/img/stickers/poliwrath.webp',7,15,2,4,false,false,NOW()-INTERVAL'1 day'),
  ('Lorelei', 1,'girl','Lorelei', '#87CEEB','dificil',  '/img/stickers/articuno.webp',8,21,3,3,false,false,NOW()),
  ('Lorelei', 2,'girl','Lorelei', '#87CEEB','normal',   '/img/stickers/lapras.webp',9,24,1,2,false,false,NOW()-INTERVAL'2 days'),
  ('Lorelei', 3,'girl','Lorelei', '#87CEEB','infernal', '/img/stickers/slowbro.webp',5,10,4,5,true, false,NOW()-INTERVAL'1 day'),
  ('Bruno',   1,'boy', 'Bruno',   '#8B4513','normal',   '/img/stickers/machamp.webp',9,22,2,3,false,false,NOW()),
  ('Bruno',   2,'boy', 'Bruno',   '#8B4513','dificil',  '/img/stickers/machoke.webp',7,18,3,2,false,false,NOW()-INTERVAL'2 days'),
  ('Bruno',   3,'boy', 'Bruno',   '#8B4513','facil',   '/img/stickers/machop.webp',10,29,0,0,false,true, NOW()-INTERVAL'1 day'),
  ('Agatha',  1,'girl','Agatha',  '#FF00FF','normal',   '/img/stickers/gengar.webp',8,19,3,3,false,false,NOW()),
  ('Agatha',  2,'girl','Agatha',  '#FF00FF','infernal', '/img/stickers/haunter.webp',4, 9,5,4,true, false,NOW()-INTERVAL'2 days'),
  ('Agatha',  3,'girl','Agatha',  '#FF00FF','dificil',  '/img/stickers/gastly.webp',7,17,2,1,false,false,NOW()-INTERVAL'1 day'),
  ('Lance',   1,'boy', 'Lance',   '#4169E1','dificil',  '/img/stickers/dragonite.webp',8,20,3,3,false,false,NOW()),
  ('Lance',   2,'boy', 'Lance',   '#4169E1','infernal', '/img/stickers/dragonair.webp',5,12,4,4,false,false,NOW()-INTERVAL'2 days'),
  ('Lance',   3,'boy', 'Lance',   '#4169E1','normal',   '/img/stickers/dratini.webp',9,24,1,2,false,false,NOW()-INTERVAL'1 day'),
  ('Blue',    1,'boy', 'Blue',    '#0000FF','normal',   '/img/stickers/blastoise.webp',9,21,2,3,false,false,NOW()),
  ('Blue',    2,'boy', 'Blue',    '#0000FF','facil',   '/img/stickers/wartortle.webp',10,28,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Blue',    3,'boy', 'Blue',    '#0000FF','dificil',  '/img/stickers/squirtle.webp',7,16,3,2,false,false,NOW()-INTERVAL'1 day'),
  ('Green',   1,'boy', 'Green',   '#00BB00','normal',   '/img/stickers/venusaur.webp',8,20,3,3,false,false,NOW()),
  ('Green',   2,'boy', 'Green',   '#00BB00','dificil',  '/img/stickers/ivysaur.webp',6,14,2,4,false,false,NOW()-INTERVAL'2 days'),
  ('Green',   3,'boy', 'Green',   '#00BB00','infernal', '/img/stickers/bulbasaur.webp',4, 8,5,3,true, false,NOW()-INTERVAL'1 day'),
  ('Red',     1,'boy', 'Red',     '#FF0000','dificil',  '/img/stickers/charizard.webp',8,21,3,2,false,false,NOW()),
  ('Red',     2,'boy', 'Red',     '#FF0000','normal',   '/img/stickers/charmeleon.webp',9,23,1,3,false,false,NOW()-INTERVAL'2 days'),
  ('Red',     3,'boy', 'Red',     '#FF0000','facil',   '/img/stickers/charmander.webp',10,30,0,0,false,true, NOW()-INTERVAL'1 day'),
  ('Yellow',  1,'girl','Yellow',  '#CCCC00','normal',   '/img/stickers/pikachu.webp',8,19,3,2,false,false,NOW()),
  ('Yellow',  2,'girl','Yellow',  '#CCCC00','facil',   '/img/stickers/raichu.webp',10,27,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Yellow',  3,'girl','Yellow',  '#CCCC00','dificil',  '/img/stickers/pichu.webp',7,16,4,3,false,false,NOW()-INTERVAL'1 day'),
  ('Leaf',    1,'girl','Leaf',    '#00FF7F','normal',   '/img/stickers/venusaur.webp',9,22,2,3,false,false,NOW()),
  ('Leaf',    2,'girl','Leaf',    '#00FF7F','dificil',  '/img/stickers/ivysaur.webp',7,17,3,1,false,false,NOW()-INTERVAL'2 days'),
  ('Leaf',    3,'girl','Leaf',    '#00FF7F','infernal', '/img/stickers/bulbasaur.webp',5,11,4,4,true, false,NOW()-INTERVAL'1 day'),
  ('Oak',     1,'boy', 'Oak',     '#8B8B8B','normal',   '/img/stickers/pikachu.webp',8,20,3,3,false,false,NOW()),
  ('Oak',     2,'boy', 'Oak',     '#8B8B8B','facil',   '/img/stickers/charizard.webp',10,29,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Oak',     3,'boy', 'Oak',     '#8B8B8B','dificil',  '/img/stickers/blastoise.webp',6,15,2,2,false,false,NOW()-INTERVAL'1 day'),
  ('Ariana',  1,'girl','Ariana',  '#FF00AA','normal',   '/img/stickers/jynx.webp',8,19,3,2,false,false,NOW()),
  ('Ariana',  2,'girl','Ariana',  '#FF00AA','facil',   '/img/stickers/smoochum.webp',10,27,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Ariana',  3,'girl','Ariana',  '#FF00AA','dificil',  '/img/stickers/magby.webp',6,14,4,3,false,false,NOW()-INTERVAL'1 day'),
  ('Atticus', 1,'boy', 'Atticus', '#333333','normal',   '/img/stickers/mewtwo.webp',9,21,2,3,false,false,NOW()),
  ('Atticus', 2,'boy', 'Atticus', '#333333','dificil',  '/img/stickers/mew.webp',7,16,3,1,false,false,NOW()-INTERVAL'2 days'),
  ('Atticus', 3,'boy', 'Atticus', '#333333','facil',   '/img/stickers/abra.webp',10,28,0,0,false,true, NOW()-INTERVAL'1 day'),
  ('Bianca',  1,'girl','Bianca',  '#FF7F50','normal',   '/img/stickers/wigglytuff.webp',8,20,3,3,false,false,NOW()),
  ('Bianca',  2,'girl','Bianca',  '#FF7F50','infernal', '/img/stickers/clefable.webp',4, 9,5,4,true, false,NOW()-INTERVAL'2 days'),
  ('Bianca',  3,'girl','Bianca',  '#FF7F50','dificil',  '/img/stickers/jigglypuff.webp',7,17,2,1,false,false,NOW()-INTERVAL'1 day'),
  ('Brendan', 1,'boy', 'Brendan', '#00AA44','dificil',  '/img/stickers/blaziken.webp',8,20,3,3,false,false,NOW()),
  ('Brendan', 2,'boy', 'Brendan', '#00AA44','infernal', '/img/stickers/combusken.webp',5,12,4,4,false,false,NOW()-INTERVAL'2 days'),
  ('Brendan', 3,'boy', 'Brendan', '#00AA44','normal',   '/img/stickers/torchic.webp',9,24,1,2,false,false,NOW()-INTERVAL'1 day'),
  ('Clair',   1,'girl','Clair',   '#4444FF','normal',   '/img/stickers/kingdra.webp',9,21,2,3,false,false,NOW()),
  ('Clair',   2,'girl','Clair',   '#4444FF','facil',   '/img/stickers/seadra.webp',10,28,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Clair',   3,'girl','Clair',   '#4444FF','dificil',  '/img/stickers/horsea.webp',7,16,3,2,false,false,NOW()-INTERVAL'1 day'),
  ('Dahlia',  1,'girl','Dahlia',  '#FF1177','normal',   '/img/stickers/arcanine.webp',8,20,3,3,false,false,NOW()),
  ('Dahlia',  2,'girl','Dahlia',  '#FF1177','dificil',  '/img/stickers/growlithe.webp',6,14,2,4,false,false,NOW()-INTERVAL'2 days'),
  ('Dahlia',  3,'girl','Dahlia',  '#FF1177','infernal', '/img/stickers/houndour.webp',4, 8,5,3,true, false,NOW()-INTERVAL'1 day'),
  ('Delia',   1,'girl','Delia',   '#9999FF','normal',   '/img/stickers/wigglytuff.webp',8,19,3,2,false,false,NOW()),
  ('Delia',   2,'girl','Delia',   '#9999FF','facil',   '/img/stickers/clefable.webp',10,27,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Delia',   3,'girl','Delia',   '#9999FF','dificil',  '/img/stickers/jigglypuff.webp',7,16,4,3,false,false,NOW()-INTERVAL'1 day'),
  ('Erreka',  1,'girl','Erreka',  '#00DDDD','normal',   '/img/stickers/vileplume.webp',9,22,2,3,false,false,NOW()),
  ('Erreka',  2,'girl','Erreka',  '#00DDDD','dificil',  '/img/stickers/bellossom.webp',7,17,3,1,false,false,NOW()-INTERVAL'2 days'),
  ('Erreka',  3,'girl','Erreka',  '#00DDDD','infernal', '/img/stickers/oddish.webp',5,11,4,4,true, false,NOW()-INTERVAL'1 day'),
  ('Flora',   1,'girl','Flora',   '#FF0099','normal',   '/img/stickers/venusaur.webp',8,20,3,3,false,false,NOW()),
  ('Flora',   2,'girl','Flora',   '#FF0099','facil',   '/img/stickers/ivysaur.webp',10,29,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Flora',   3,'girl','Flora',   '#FF0099','dificil',  '/img/stickers/bulbasaur.webp',6,15,2,2,false,false,NOW()-INTERVAL'1 day'),
  ('Fuchsia', 1,'girl','Fuchsia', '#CC00FF','normal',   '/img/stickers/weezing.webp',8,19,3,2,false,false,NOW()),
  ('Fuchsia', 2,'girl','Fuchsia', '#CC00FF','dificil',  '/img/stickers/muk.webp',7,15,2,4,false,false,NOW()-INTERVAL'2 days'),
  ('Fuchsia', 3,'girl','Fuchsia', '#CC00FF','facil',   '/img/stickers/golbat.webp',10,27,0,0,false,true, NOW()-INTERVAL'1 day'),
  ('Giselle', 1,'girl','Giselle', '#FFAAAA','normal',   '/img/stickers/articuno.webp',9,21,2,3,false,false,NOW()),
  ('Giselle', 2,'girl','Giselle', '#FFAAAA','infernal', '/img/stickers/lapras.webp',4, 9,5,4,true, false,NOW()-INTERVAL'2 days'),
  ('Giselle', 3,'girl','Giselle', '#FFAAAA','dificil',  '/img/stickers/slowbro.webp',7,17,2,1,false,false,NOW()-INTERVAL'1 day'),
  ('Grant',   1,'boy', 'Grant',   '#00DDAA','dificil',  '/img/stickers/machamp.webp',8,20,3,3,false,false,NOW()),
  ('Grant',   2,'boy', 'Grant',   '#00DDAA','normal',   '/img/stickers/machoke.webp',9,23,1,2,false,false,NOW()-INTERVAL'2 days'),
  ('Grant',   3,'boy', 'Grant',   '#00DDAA','facil',   '/img/stickers/machop.webp',10,30,0,0,false,true, NOW()-INTERVAL'1 day'),
  ('Harlene', 1,'girl','Harlene', '#DD00DD','normal',   '/img/stickers/gengar.webp',8,19,3,2,false,false,NOW()),
  ('Harlene', 2,'girl','Harlene', '#DD00DD','facil',   '/img/stickers/haunter.webp',10,28,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Harlene', 3,'girl','Harlene', '#DD00DD','dificil',  '/img/stickers/gastly.webp',6,14,4,3,false,false,NOW()-INTERVAL'1 day'),
  ('Iris',    1,'girl','Iris',    '#FF6644','normal',   '/img/stickers/dragonite.webp',9,21,2,3,false,false,NOW()),
  ('Iris',    2,'girl','Iris',    '#FF6644','dificil',  '/img/stickers/dragonair.webp',7,16,3,1,false,false,NOW()-INTERVAL'2 days'),
  ('Iris',    3,'girl','Iris',    '#FF6644','infernal', '/img/stickers/dratini.webp',4, 8,5,5,true, false,NOW()-INTERVAL'1 day'),
  ('Irina',   1,'girl','Irina',   '#00FF66','dificil',  '/img/stickers/blastoise.webp',8,20,3,3,false,false,NOW()),
  ('Irina',   2,'girl','Irina',   '#00FF66','normal',   '/img/stickers/wartortle.webp',9,23,1,2,false,false,NOW()-INTERVAL'2 days'),
  ('Irina',   3,'girl','Irina',   '#00FF66','facil',   '/img/stickers/squirtle.webp',10,30,0,0,false,true, NOW()-INTERVAL'1 day'),
  ('Jackie',  1,'boy', 'Jackie',  '#FFCC00','normal',   '/img/stickers/charizard.webp',8,20,3,3,false,false,NOW()),
  ('Jackie',  2,'boy', 'Jackie',  '#FFCC00','infernal', '/img/stickers/charmeleon.webp',4, 9,5,4,true, false,NOW()-INTERVAL'2 days'),
  ('Jackie',  3,'boy', 'Jackie',  '#FFCC00','dificil',  '/img/stickers/charmander.webp',7,17,2,1,false,false,NOW()-INTERVAL'1 day'),
  ('Jasmine', 1,'girl','Jasmine', '#00CCFF','normal',   '/img/stickers/pikachu.webp',9,22,2,3,false,false,NOW()),
  ('Jasmine', 2,'girl','Jasmine', '#00CCFF','dificil',  '/img/stickers/raichu.webp',7,17,3,1,false,false,NOW()-INTERVAL'2 days'),
  ('Jasmine', 3,'girl','Jasmine', '#00CCFF','facil',   '/img/stickers/pichu.webp',10,29,0,0,false,true, NOW()-INTERVAL'1 day'),
  ('Juan',    1,'boy', 'Juan',    '#CC0066','normal',   '/img/stickers/venusaur.webp',8,20,3,3,false,false,NOW()),
  ('Juan',    2,'boy', 'Juan',    '#CC0066','facil',   '/img/stickers/ivysaur.webp',10,28,0,0,false,true, NOW()-INTERVAL'2 days'),
  ('Juan',    3,'boy', 'Juan',    '#CC0066','dificil',  '/img/stickers/bulbasaur.webp',6,14,4,3,false,false,NOW()-INTERVAL'1 day'),
  ('Kaida',   1,'girl','Kaida',   '#66CCFF','normal',   '/img/stickers/jynx.webp',9,21,2,3,false,false,NOW()),
  ('Kaida',   2,'girl','Kaida',   '#66CCFF','infernal', '/img/stickers/smoochum.webp',4, 9,5,4,true, false,NOW()-INTERVAL'2 days'),
  ('Kaida',   3,'girl','Kaida',   '#66CCFF','dificil',  '/img/stickers/magby.webp',7,17,2,1,false,false,NOW()-INTERVAL'1 day'),
  ('Klara',   1,'girl','Klara',   '#FF00CC','dificil',  '/img/stickers/mewtwo.webp',8,20,3,3,false,false,NOW()),
  ('Klara',   2,'girl','Klara',   '#FF00CC','normal',   '/img/stickers/mew.webp',9,23,1,2,false,false,NOW()-INTERVAL'2 days'),
  ('Klara',   3,'girl','Klara',   '#FF00CC','facil',   '/img/stickers/abra.webp',10,30,0,0,false,true, NOW()-INTERVAL'1 day')
) AS s(username,slot_number,explorer,explorer_name,color,difficulty_id,sticker,hp,pokeball,position_r,position_c,is_game_over,is_goal,updated_at)
ON u.username = s.username;

-- ============================================================================
-- 3. INSERTAR POKÉMON CAPTURADOS (subquery por username + slot_number)
-- ============================================================================

INSERT INTO captured_pokemon (user_id, slot_id, pokemon_id, pokemon_name, captured_at)
SELECT u.id, gs.id, p.pokemon_id, p.pokemon_name, p.captured_at
FROM (VALUES
  ('Luis',    1, 25,'PIKACHU',    NOW()-INTERVAL'5 hours'),
  ('Luis',    1, 26,'RAICHU',     NOW()-INTERVAL'4 hours'),
  ('Luis',    1,  4,'CHARMANDER', NOW()-INTERVAL'3 hours'),
  ('Luis',    1,  7,'SQUIRTLE',   NOW()-INTERVAL'2 hours'),
  ('Luis',    1, 52,'MEOWTH',     NOW()-INTERVAL'1 hour'),
  ('Luis',    3,  1,'BULBASAUR',  NOW()-INTERVAL'30 minutes'),
  ('Luis',    3,  2,'IVYSAUR',    NOW()-INTERVAL'20 minutes'),
  ('Jorge',   1, 58,'GROWLITHE',  NOW()-INTERVAL'6 hours'),
  ('Jorge',   1, 77,'PONYTA',     NOW()-INTERVAL'5 hours'),
  ('Jorge',   1, 37,'VULPIX',     NOW()-INTERVAL'4 hours'),
  ('Jorge',   1, 38,'NINETALES',  NOW()-INTERVAL'3 hours'),
  ('Jorge',   3, 54,'PSYDUCK',    NOW()-INTERVAL'2 hours'),
  ('Jorge',   3, 55,'GOLDUCK',    NOW()-INTERVAL'1 hour'),
  ('Ash',     1, 25,'PIKACHU',    NOW()-INTERVAL'4 hours'),
  ('Ash',     1, 95,'ONIX',       NOW()-INTERVAL'3 hours'),
  ('Ash',     1, 52,'MEOWTH',     NOW()-INTERVAL'2 hours'),
  ('Ash',     1, 21,'SPEAROW',    NOW()-INTERVAL'1 hour'),
  ('Ash',     3, 16,'PIDGEOT',    NOW()-INTERVAL'30 minutes'),
  ('Ash',     3,149,'DRAGONITE',  NOW()-INTERVAL'20 minutes'),
  ('Misty',   1, 54,'PSYDUCK',    NOW()-INTERVAL'5 hours'),
  ('Misty',   1, 55,'GOLDUCK',    NOW()-INTERVAL'4 hours'),
  ('Misty',   1, 60,'POLIWAG',    NOW()-INTERVAL'3 hours'),
  ('Misty',   1, 86,'SEEL',       NOW()-INTERVAL'2 hours'),
  ('Misty',   2, 90,'SHELLDER',   NOW()-INTERVAL'1 hour'),
  ('Misty',   2, 79,'SLOWPOKE',   NOW()-INTERVAL'30 minutes'),
  ('Brock',   1, 95,'ONIX',       NOW()-INTERVAL'4 hours'),
  ('Brock',   1,111,'RHYHORN',    NOW()-INTERVAL'3 hours'),
  ('Brock',   1, 27,'SANDSHREW',  NOW()-INTERVAL'2 hours'),
  ('Brock',   1, 74,'GEODUDE',    NOW()-INTERVAL'1 hour'),
  ('Brock',   2, 50,'DIGLETT',    NOW()-INTERVAL'30 minutes'),
  ('Brock',   2, 31,'NIDOQUEEN',  NOW()-INTERVAL'20 minutes'),
  ('Cynthia', 1,149,'DRAGONITE',  NOW()-INTERVAL'5 hours'),
  ('Cynthia', 1,145,'ZAPDOS',     NOW()-INTERVAL'4 hours'),
  ('Cynthia', 1,146,'MOLTRES',    NOW()-INTERVAL'3 hours'),
  ('Cynthia', 1,144,'ARTICUNO',   NOW()-INTERVAL'2 hours'),
  ('Cynthia', 1,150,'MEWTWO',     NOW()-INTERVAL'1 hour'),
  ('Cynthia', 2, 25,'PIKACHU',    NOW()-INTERVAL'30 minutes'),
  ('Blaine',  1, 37,'VULPIX',     NOW()-INTERVAL'4 hours'),
  ('Blaine',  1, 38,'NINETALES',  NOW()-INTERVAL'3 hours'),
  ('Blaine',  1, 58,'GROWLITHE',  NOW()-INTERVAL'2 hours'),
  ('Blaine',  1, 77,'PONYTA',     NOW()-INTERVAL'1 hour'),
  ('Blaine',  3,  4,'CHARMANDER', NOW()-INTERVAL'30 minutes'),
  ('Blaine',  3,  5,'CHARMELEON', NOW()-INTERVAL'20 minutes'),
  ('Sabrina', 1, 63,'ABRA',       NOW()-INTERVAL'4 hours'),
  ('Sabrina', 1, 64,'KADABRA',    NOW()-INTERVAL'3 hours'),
  ('Sabrina', 1, 65,'ALAKAZAM',   NOW()-INTERVAL'2 hours'),
  ('Sabrina', 1, 92,'GASTLY',     NOW()-INTERVAL'1 hour'),
  ('Sabrina', 3, 25,'PIKACHU',    NOW()-INTERVAL'30 minutes'),
  ('Giovanni',1, 52,'MEOWTH',     NOW()-INTERVAL'4 hours'),
  ('Giovanni',1, 27,'SANDSHREW',  NOW()-INTERVAL'3 hours'),
  ('Giovanni',1, 74,'GEODUDE',    NOW()-INTERVAL'2 hours'),
  ('Giovanni',1, 95,'ONIX',       NOW()-INTERVAL'1 hour'),
  ('Giovanni',3,149,'DRAGONITE',  NOW()-INTERVAL'30 minutes'),
  ('Jessie',  1, 29,'NIDORAN',    NOW()-INTERVAL'4 hours'),
  ('Jessie',  1, 30,'NIDORINA',   NOW()-INTERVAL'3 hours'),
  ('Jessie',  1, 31,'NIDOQUEEN',  NOW()-INTERVAL'2 hours'),
  ('Jessie',  2, 25,'PIKACHU',    NOW()-INTERVAL'1 hour'),
  ('James',   1,  7,'SQUIRTLE',   NOW()-INTERVAL'4 hours'),
  ('James',   1,  8,'WARTORTLE',  NOW()-INTERVAL'3 hours'),
  ('James',   1,  9,'BLASTOISE',  NOW()-INTERVAL'2 hours'),
  ('James',   1, 60,'POLIWAG',    NOW()-INTERVAL'1 hour'),
  ('James',   3, 25,'PIKACHU',    NOW()-INTERVAL'30 minutes'),
  ('Meowth',  1, 52,'MEOWTH',     NOW()-INTERVAL'4 hours'),
  ('Meowth',  1, 25,'PIKACHU',    NOW()-INTERVAL'3 hours'),
  ('Meowth',  1, 54,'PSYDUCK',    NOW()-INTERVAL'2 hours'),
  ('Meowth',  3, 16,'PIDGEOT',    NOW()-INTERVAL'30 minutes'),
  ('Whitney', 1, 54,'PSYDUCK',    NOW()-INTERVAL'4 hours'),
  ('Whitney', 1, 55,'GOLDUCK',    NOW()-INTERVAL'3 hours'),
  ('Whitney', 1, 52,'MEOWTH',     NOW()-INTERVAL'2 hours'),
  ('Whitney', 2, 25,'PIKACHU',    NOW()-INTERVAL'1 hour'),
  ('Erika',   1, 69,'BELLSPROUT', NOW()-INTERVAL'4 hours'),
  ('Erika',   1, 70,'WEEPINBELL', NOW()-INTERVAL'3 hours'),
  ('Erika',   1, 71,'VICTREEBEL', NOW()-INTERVAL'2 hours'),
  ('Erika',   1,  1,'BULBASAUR',  NOW()-INTERVAL'1 hour'),
  ('Surge',   1, 25,'PIKACHU',    NOW()-INTERVAL'4 hours'),
  ('Surge',   1, 26,'RAICHU',     NOW()-INTERVAL'3 hours'),
  ('Surge',   1,145,'ZAPDOS',     NOW()-INTERVAL'2 hours'),
  ('Surge',   3,  4,'CHARMANDER', NOW()-INTERVAL'30 minutes'),
  ('Koga',    1, 92,'GASTLY',     NOW()-INTERVAL'4 hours'),
  ('Koga',    1, 93,'HAUNTER',    NOW()-INTERVAL'3 hours'),
  ('Koga',    1, 94,'GENGAR',     NOW()-INTERVAL'2 hours'),
  ('Koga',    3, 29,'NIDORAN',    NOW()-INTERVAL'30 minutes'),
  ('Janine',  1, 29,'NIDORAN',    NOW()-INTERVAL'4 hours'),
  ('Janine',  1, 30,'NIDORINA',   NOW()-INTERVAL'3 hours'),
  ('Janine',  1, 31,'NIDOQUEEN',  NOW()-INTERVAL'2 hours'),
  ('Janine',  2, 25,'PIKACHU',    NOW()-INTERVAL'30 minutes'),
  ('Lorelei', 1, 86,'SEEL',       NOW()-INTERVAL'4 hours'),
  ('Lorelei', 1, 87,'DEWGONG',    NOW()-INTERVAL'3 hours'),
  ('Lorelei', 1, 90,'SHELLDER',   NOW()-INTERVAL'2 hours'),
  ('Lorelei', 1,144,'ARTICUNO',   NOW()-INTERVAL'1 hour'),
  ('Bruno',   1, 95,'ONIX',       NOW()-INTERVAL'4 hours'),
  ('Bruno',   1,104,'CUBONE',     NOW()-INTERVAL'3 hours'),
  ('Bruno',   1,105,'MAROWAK',    NOW()-INTERVAL'2 hours'),
  ('Bruno',   3,111,'RHYHORN',    NOW()-INTERVAL'30 minutes'),
  ('Agatha',  1, 92,'GASTLY',     NOW()-INTERVAL'4 hours'),
  ('Agatha',  1, 93,'HAUNTER',    NOW()-INTERVAL'3 hours'),
  ('Agatha',  1, 94,'GENGAR',     NOW()-INTERVAL'2 hours'),
  ('Agatha',  3,109,'KOFFING',    NOW()-INTERVAL'30 minutes'),
  ('Lance',   1,149,'DRAGONITE',  NOW()-INTERVAL'4 hours'),
  ('Lance',   1,147,'DRATINI',    NOW()-INTERVAL'3 hours'),
  ('Lance',   1,148,'DRAGONAIR',  NOW()-INTERVAL'2 hours'),
  ('Lance',   1, 25,'PIKACHU',    NOW()-INTERVAL'1 hour'),
  ('Lance',   2,145,'ZAPDOS',     NOW()-INTERVAL'30 minutes'),
  ('Blue',    1, 25,'PIKACHU',    NOW()-INTERVAL'4 hours'),
  ('Blue',    1,  4,'CHARMANDER', NOW()-INTERVAL'3 hours'),
  ('Blue',    1,  7,'SQUIRTLE',   NOW()-INTERVAL'2 hours'),
  ('Blue',    1,  1,'BULBASAUR',  NOW()-INTERVAL'1 hour'),
  ('Blue',    2,149,'DRAGONITE',  NOW()-INTERVAL'30 minutes'),
  ('Green',   1,  1,'BULBASAUR',  NOW()-INTERVAL'4 hours'),
  ('Green',   1,  2,'IVYSAUR',    NOW()-INTERVAL'3 hours'),
  ('Green',   1,  3,'VENUSAUR',   NOW()-INTERVAL'2 hours'),
  ('Red',     1,  4,'CHARMANDER', NOW()-INTERVAL'4 hours'),
  ('Red',     1,  5,'CHARMELEON', NOW()-INTERVAL'3 hours'),
  ('Red',     1,  6,'CHARIZARD',  NOW()-INTERVAL'2 hours'),
  ('Red',     3, 25,'PIKACHU',    NOW()-INTERVAL'30 minutes'),
  ('Yellow',  1, 25,'PIKACHU',    NOW()-INTERVAL'4 hours'),
  ('Yellow',  1, 26,'RAICHU',     NOW()-INTERVAL'3 hours'),
  ('Yellow',  1, 35,'CLEFAIRY',   NOW()-INTERVAL'2 hours'),
  ('Yellow',  2, 39,'JIGGLYPUFF', NOW()-INTERVAL'1 hour'),
  ('Leaf',    1,  1,'BULBASAUR',  NOW()-INTERVAL'4 hours'),
  ('Leaf',    1,  7,'SQUIRTLE',   NOW()-INTERVAL'3 hours'),
  ('Leaf',    1, 25,'PIKACHU',    NOW()-INTERVAL'2 hours'),
  ('Leaf',    3,149,'DRAGONITE',  NOW()-INTERVAL'30 minutes'),
  ('Oak',     1, 25,'PIKACHU',    NOW()-INTERVAL'4 hours'),
  ('Oak',     1,  1,'BULBASAUR',  NOW()-INTERVAL'3 hours'),
  ('Oak',     1,  4,'CHARMANDER', NOW()-INTERVAL'2 hours'),
  ('Oak',     1,  7,'SQUIRTLE',   NOW()-INTERVAL'1 hour'),
  ('Oak',     2,149,'DRAGONITE',  NOW()-INTERVAL'30 minutes'),
  ('Ariana',  1, 52,'MEOWTH',     NOW()-INTERVAL'4 hours'),
  ('Ariana',  1, 25,'PIKACHU',    NOW()-INTERVAL'3 hours'),
  ('Ariana',  1, 54,'PSYDUCK',    NOW()-INTERVAL'2 hours'),
  ('Ariana',  2, 16,'PIDGEOT',    NOW()-INTERVAL'30 minutes'),
  ('Atticus', 1, 95,'ONIX',       NOW()-INTERVAL'4 hours'),
  ('Atticus', 1,111,'RHYHORN',    NOW()-INTERVAL'3 hours'),
  ('Atticus', 1, 27,'SANDSHREW',  NOW()-INTERVAL'2 hours'),
  ('Atticus', 3, 25,'PIKACHU',    NOW()-INTERVAL'30 minutes'),
  ('Bianca',  1, 37,'VULPIX',     NOW()-INTERVAL'4 hours'),
  ('Bianca',  1, 38,'NINETALES',  NOW()-INTERVAL'3 hours'),
  ('Bianca',  1, 58,'GROWLITHE',  NOW()-INTERVAL'2 hours'),
  ('Bianca',  3,  4,'CHARMANDER', NOW()-INTERVAL'30 minutes'),
  ('Brendan', 1, 63,'ABRA',       NOW()-INTERVAL'4 hours'),
  ('Brendan', 1, 64,'KADABRA',    NOW()-INTERVAL'3 hours'),
  ('Brendan', 1, 65,'ALAKAZAM',   NOW()-INTERVAL'2 hours'),
  ('Brendan', 2, 25,'PIKACHU',    NOW()-INTERVAL'30 minutes'),
  ('Clair',   1, 54,'PSYDUCK',    NOW()-INTERVAL'4 hours'),
  ('Clair',   1, 55,'GOLDUCK',    NOW()-INTERVAL'3 hours'),
  ('Clair',   1, 52,'MEOWTH',     NOW()-INTERVAL'2 hours'),
  ('Clair',   2, 25,'PIKACHU',    NOW()-INTERVAL'1 hour'),
  ('Dahlia',  1, 69,'BELLSPROUT', NOW()-INTERVAL'4 hours'),
  ('Dahlia',  1, 70,'WEEPINBELL', NOW()-INTERVAL'3 hours'),
  ('Dahlia',  1, 71,'VICTREEBEL', NOW()-INTERVAL'2 hours'),
  ('Dahlia',  1,  1,'BULBASAUR',  NOW()-INTERVAL'1 hour'),
  ('Delia',   1, 25,'PIKACHU',    NOW()-INTERVAL'4 hours'),
  ('Delia',   1, 26,'RAICHU',     NOW()-INTERVAL'3 hours'),
  ('Delia',   1,145,'ZAPDOS',     NOW()-INTERVAL'2 hours'),
  ('Delia',   3,  4,'CHARMANDER', NOW()-INTERVAL'30 minutes'),
  ('Erreka',  1, 92,'GASTLY',     NOW()-INTERVAL'4 hours'),
  ('Erreka',  1, 93,'HAUNTER',    NOW()-INTERVAL'3 hours'),
  ('Erreka',  1, 94,'GENGAR',     NOW()-INTERVAL'2 hours'),
  ('Erreka',  3, 29,'NIDORAN',    NOW()-INTERVAL'30 minutes'),
  ('Flora',   1, 29,'NIDORAN',    NOW()-INTERVAL'4 hours'),
  ('Flora',   1, 30,'NIDORINA',   NOW()-INTERVAL'3 hours'),
  ('Flora',   1, 31,'NIDOQUEEN',  NOW()-INTERVAL'2 hours'),
  ('Flora',   3, 25,'PIKACHU',    NOW()-INTERVAL'1 hour'),
  ('Fuchsia', 1, 86,'SEEL',       NOW()-INTERVAL'4 hours'),
  ('Fuchsia', 1, 87,'DEWGONG',    NOW()-INTERVAL'3 hours'),
  ('Fuchsia', 1, 90,'SHELLDER',   NOW()-INTERVAL'2 hours'),
  ('Fuchsia', 3, 25,'PIKACHU',    NOW()-INTERVAL'30 minutes'),
  ('Giselle', 1, 95,'ONIX',       NOW()-INTERVAL'4 hours'),
  ('Giselle', 1,104,'CUBONE',     NOW()-INTERVAL'3 hours'),
  ('Giselle', 1,105,'MAROWAK',    NOW()-INTERVAL'2 hours'),
  ('Giselle', 3,111,'RHYHORN',    NOW()-INTERVAL'30 minutes'),
  ('Grant',   1, 92,'GASTLY',     NOW()-INTERVAL'4 hours'),
  ('Grant',   1, 93,'HAUNTER',    NOW()-INTERVAL'3 hours'),
  ('Grant',   1, 94,'GENGAR',     NOW()-INTERVAL'2 hours'),
  ('Grant',   3,109,'KOFFING',    NOW()-INTERVAL'30 minutes'),
  ('Harlene', 1,149,'DRAGONITE',  NOW()-INTERVAL'4 hours'),
  ('Harlene', 1,147,'DRATINI',    NOW()-INTERVAL'3 hours'),
  ('Harlene', 1,148,'DRAGONAIR',  NOW()-INTERVAL'2 hours'),
  ('Harlene', 1, 25,'PIKACHU',    NOW()-INTERVAL'1 hour'),
  ('Iris',    1, 25,'PIKACHU',    NOW()-INTERVAL'4 hours'),
  ('Iris',    1,  4,'CHARMANDER', NOW()-INTERVAL'3 hours'),
  ('Iris',    1,  7,'SQUIRTLE',   NOW()-INTERVAL'2 hours'),
  ('Iris',    1,  1,'BULBASAUR',  NOW()-INTERVAL'1 hour'),
  ('Irina',   1,149,'DRAGONITE',  NOW()-INTERVAL'4 hours'),
  ('Irina',   1,145,'ZAPDOS',     NOW()-INTERVAL'3 hours'),
  ('Irina',   1,146,'MOLTRES',    NOW()-INTERVAL'2 hours'),
  ('Irina',   3, 25,'PIKACHU',    NOW()-INTERVAL'30 minutes'),
  ('Jackie',  1, 37,'VULPIX',     NOW()-INTERVAL'4 hours'),
  ('Jackie',  1, 38,'NINETALES',  NOW()-INTERVAL'3 hours'),
  ('Jackie',  1, 58,'GROWLITHE',  NOW()-INTERVAL'2 hours'),
  ('Jackie',  3, 77,'PONYTA',     NOW()-INTERVAL'30 minutes'),
  ('Jasmine', 1, 63,'ABRA',       NOW()-INTERVAL'4 hours'),
  ('Jasmine', 1, 64,'KADABRA',    NOW()-INTERVAL'3 hours'),
  ('Jasmine', 1, 65,'ALAKAZAM',   NOW()-INTERVAL'2 hours'),
  ('Jasmine', 3, 92,'GASTLY',     NOW()-INTERVAL'30 minutes'),
  ('Juan',    1, 25,'PIKACHU',    NOW()-INTERVAL'4 hours'),
  ('Juan',    1, 26,'RAICHU',     NOW()-INTERVAL'3 hours'),
  ('Juan',    1, 35,'CLEFAIRY',   NOW()-INTERVAL'2 hours'),
  ('Juan',    2, 39,'JIGGLYPUFF', NOW()-INTERVAL'1 hour'),
  ('Kaida',   1,  1,'BULBASAUR',  NOW()-INTERVAL'4 hours'),
  ('Kaida',   1,  7,'SQUIRTLE',   NOW()-INTERVAL'3 hours'),
  ('Kaida',   1, 25,'PIKACHU',    NOW()-INTERVAL'2 hours'),
  ('Kaida',   3,149,'DRAGONITE',  NOW()-INTERVAL'30 minutes'),
  ('Klara',   1, 25,'PIKACHU',    NOW()-INTERVAL'4 hours'),
  ('Klara',   1,  1,'BULBASAUR',  NOW()-INTERVAL'3 hours'),
  ('Klara',   1,  4,'CHARMANDER', NOW()-INTERVAL'2 hours'),
  ('Klara',   1,  7,'SQUIRTLE',   NOW()-INTERVAL'1 hour'),
  ('Klara',   2,149,'DRAGONITE',  NOW()-INTERVAL'30 minutes')
) AS p(username, slot_number, pokemon_id, pokemon_name, captured_at)
JOIN users u ON u.username = p.username
JOIN game_slots gs ON gs.user_id = u.id AND gs.slot_number = p.slot_number;

-- ============================================================================
-- 4. INSERTAR RANKINGS (subquery por username)
-- ============================================================================

INSERT INTO ranking (user_id, captured_count, escaped_count, difficulty_id, explorer_name, completed_at)
SELECT u.id, r.captured_count, r.escaped_count, r.difficulty_id, r.explorer_name, r.completed_at
FROM users u
JOIN (VALUES
  ('Luis',    15, 2,'normal',   'Luis',     NOW()-INTERVAL'5 days'),
  ('Luis',    12, 4,'dificil',  'Luis',     NOW()-INTERVAL'3 days'),
  ('Luis',    20, 0,'facil',    'Luis',     NOW()-INTERVAL'1 day'),
  ('Jorge',   18, 1,'normal',   'Jorge',    NOW()-INTERVAL'4 days'),
  ('Jorge',   10, 6,'infernal', 'Jorge',    NOW()-INTERVAL'2 days'),
  ('Jorge',   16, 2,'dificil',  'Jorge',    NOW()),
  ('Ash',     16, 1,'normal',   'Ash',      NOW()-INTERVAL'6 days'),
  ('Ash',     12, 5,'dificil',  'Ash',      NOW()-INTERVAL'4 days'),
  ('Ash',     20, 0,'facil',    'Ash',      NOW()-INTERVAL'2 days'),
  ('Ash',     14, 3,'normal',   'Ash',      NOW()),
  ('Misty',   14, 2,'normal',   'Misty',    NOW()-INTERVAL'5 days'),
  ('Misty',   11, 6,'dificil',  'Misty',    NOW()-INTERVAL'3 days'),
  ('Misty',    8, 9,'infernal', 'Misty',    NOW()-INTERVAL'1 day'),
  ('Misty',   13, 4,'normal',   'Misty',    NOW()),
  ('Brock',   13, 3,'normal',   'Brock',    NOW()-INTERVAL'5 days'),
  ('Brock',   19, 1,'facil',    'Brock',    NOW()-INTERVAL'3 days'),
  ('Brock',   11, 7,'dificil',  'Brock',    NOW()-INTERVAL'1 day'),
  ('Cynthia', 17, 2,'dificil',  'Cynthia',  NOW()-INTERVAL'4 days'),
  ('Cynthia', 19, 0,'normal',   'Cynthia',  NOW()-INTERVAL'2 days'),
  ('Cynthia',  9, 8,'infernal', 'Cynthia',  NOW()),
  ('Blaine',  12, 4,'dificil',  'Blaine',   NOW()-INTERVAL'5 days'),
  ('Blaine',   7,10,'infernal', 'Blaine',   NOW()-INTERVAL'3 days'),
  ('Blaine',  15, 2,'normal',   'Blaine',   NOW()-INTERVAL'1 day'),
  ('Sabrina', 14, 3,'normal',   'Sabrina',  NOW()-INTERVAL'4 days'),
  ('Sabrina', 11, 6,'dificil',  'Sabrina',  NOW()-INTERVAL'2 days'),
  ('Sabrina', 18, 1,'facil',    'Sabrina',  NOW()),
  ('Giovanni',13, 4,'normal',   'Giovanni', NOW()-INTERVAL'5 days'),
  ('Giovanni', 6,11,'infernal', 'Giovanni', NOW()-INTERVAL'3 days'),
  ('Giovanni',12, 5,'dificil',  'Giovanni', NOW()-INTERVAL'1 day'),
  ('Jessie',  11, 5,'normal',   'Jessie',   NOW()-INTERVAL'4 days'),
  ('Jessie',  17, 2,'facil',    'Jessie',   NOW()-INTERVAL'2 days'),
  ('Jessie',  10, 7,'dificil',  'Jessie',   NOW()),
  ('James',   12, 4,'normal',   'James',    NOW()-INTERVAL'5 days'),
  ('James',    9, 8,'dificil',  'James',    NOW()-INTERVAL'3 days'),
  ('James',   16, 3,'facil',    'James',    NOW()-INTERVAL'1 day'),
  ('Meowth',  14, 2,'normal',   'Meowth',   NOW()-INTERVAL'4 days'),
  ('Meowth',   8, 9,'infernal', 'Meowth',   NOW()-INTERVAL'2 days'),
  ('Meowth',  18, 1,'facil',    'Meowth',   NOW()),
  ('Whitney', 13, 3,'normal',   'Whitney',  NOW()-INTERVAL'5 days'),
  ('Whitney', 17, 2,'facil',    'Whitney',  NOW()-INTERVAL'3 days'),
  ('Whitney', 11, 6,'dificil',  'Whitney',  NOW()-INTERVAL'1 day'),
  ('Erika',   15, 1,'normal',   'Erika',    NOW()-INTERVAL'4 days'),
  ('Erika',   10, 7,'dificil',  'Erika',    NOW()-INTERVAL'2 days'),
  ('Erika',    7,10,'infernal', 'Erika',    NOW()),
  ('Surge',   16, 2,'dificil',  'Surge',    NOW()-INTERVAL'5 days'),
  ('Surge',   14, 3,'normal',   'Surge',    NOW()-INTERVAL'3 days'),
  ('Surge',   19, 0,'facil',    'Surge',    NOW()-INTERVAL'1 day'),
  ('Koga',    12, 4,'normal',   'Koga',     NOW()-INTERVAL'4 days'),
  ('Koga',     6,11,'infernal', 'Koga',     NOW()-INTERVAL'2 days'),
  ('Koga',    13, 5,'dificil',  'Koga',     NOW()),
  ('Janine',  14, 2,'normal',   'Janine',   NOW()-INTERVAL'5 days'),
  ('Janine',  17, 2,'facil',    'Janine',   NOW()-INTERVAL'3 days'),
  ('Janine',  10, 7,'dificil',  'Janine',   NOW()-INTERVAL'1 day'),
  ('Lorelei', 16, 3,'dificil',  'Lorelei',  NOW()-INTERVAL'4 days'),
  ('Lorelei', 15, 2,'normal',   'Lorelei',  NOW()-INTERVAL'2 days'),
  ('Lorelei',  8, 9,'infernal', 'Lorelei',  NOW()),
  ('Bruno',   14, 3,'normal',   'Bruno',    NOW()-INTERVAL'5 days'),
  ('Bruno',   12, 5,'dificil',  'Bruno',    NOW()-INTERVAL'3 days'),
  ('Bruno',   18, 1,'facil',    'Bruno',    NOW()-INTERVAL'1 day'),
  ('Agatha',  13, 4,'normal',   'Agatha',   NOW()-INTERVAL'4 days'),
  ('Agatha',   7,10,'infernal', 'Agatha',   NOW()-INTERVAL'2 days'),
  ('Agatha',  11, 6,'dificil',  'Agatha',   NOW()),
  ('Lance',   17, 2,'dificil',  'Lance',    NOW()-INTERVAL'5 days'),
  ('Lance',    9, 8,'infernal', 'Lance',    NOW()-INTERVAL'3 days'),
  ('Lance',   15, 2,'normal',   'Lance',    NOW()-INTERVAL'1 day'),
  ('Blue',    15, 2,'normal',   'Blue',     NOW()-INTERVAL'4 days'),
  ('Blue',    18, 1,'facil',    'Blue',     NOW()-INTERVAL'2 days'),
  ('Blue',    12, 5,'dificil',  'Blue',     NOW()),
  ('Green',   13, 3,'normal',   'Green',    NOW()-INTERVAL'5 days'),
  ('Green',    8, 9,'infernal', 'Green',    NOW()-INTERVAL'3 days'),
  ('Green',   14, 4,'dificil',  'Green',    NOW()-INTERVAL'1 day'),
  ('Red',     16, 2,'dificil',  'Red',      NOW()-INTERVAL'4 days'),
  ('Red',     14, 3,'normal',   'Red',      NOW()-INTERVAL'2 days'),
  ('Red',     19, 0,'facil',    'Red',      NOW()),
  ('Yellow',  12, 4,'normal',   'Yellow',   NOW()-INTERVAL'5 days'),
  ('Yellow',  17, 2,'facil',    'Yellow',   NOW()-INTERVAL'3 days'),
  ('Yellow',  10, 7,'dificil',  'Yellow',   NOW()-INTERVAL'1 day'),
  ('Leaf',    14, 2,'normal',   'Leaf',     NOW()-INTERVAL'4 days'),
  ('Leaf',    11, 6,'dificil',  'Leaf',     NOW()-INTERVAL'2 days'),
  ('Leaf',     8, 9,'infernal', 'Leaf',     NOW()),
  ('Oak',     15, 1,'normal',   'Oak',      NOW()-INTERVAL'5 days'),
  ('Oak',     18, 1,'facil',    'Oak',      NOW()-INTERVAL'3 days'),
  ('Oak',     12, 5,'dificil',  'Oak',      NOW()-INTERVAL'1 day'),
  ('Ariana',  14, 2,'normal',   'Ariana',   NOW()-INTERVAL'4 days'),
  ('Ariana',  17, 2,'facil',    'Ariana',   NOW()-INTERVAL'2 days'),
  ('Ariana',  10, 7,'dificil',  'Ariana',   NOW()),
  ('Atticus', 13, 3,'normal',   'Atticus',  NOW()-INTERVAL'5 days'),
  ('Atticus',  8, 9,'infernal', 'Atticus',  NOW()-INTERVAL'3 days'),
  ('Atticus', 14, 4,'dificil',  'Atticus',  NOW()-INTERVAL'1 day'),
  ('Bianca',  16, 2,'dificil',  'Bianca',   NOW()-INTERVAL'4 days'),
  ('Bianca',  14, 3,'normal',   'Bianca',   NOW()-INTERVAL'2 days'),
  ('Bianca',  19, 0,'facil',    'Bianca',   NOW()),
  ('Brendan', 12, 4,'normal',   'Brendan',  NOW()-INTERVAL'5 days'),
  ('Brendan', 17, 2,'facil',    'Brendan',  NOW()-INTERVAL'3 days'),
  ('Brendan', 10, 7,'dificil',  'Brendan',  NOW()-INTERVAL'1 day'),
  ('Clair',   14, 2,'normal',   'Clair',    NOW()-INTERVAL'4 days'),
  ('Clair',   11, 6,'dificil',  'Clair',    NOW()-INTERVAL'2 days'),
  ('Clair',   18, 1,'facil',    'Clair',    NOW()),
  ('Dahlia',  15, 1,'normal',   'Dahlia',   NOW()-INTERVAL'5 days'),
  ('Dahlia',  10, 7,'dificil',  'Dahlia',   NOW()-INTERVAL'3 days'),
  ('Dahlia',   7,10,'infernal', 'Dahlia',   NOW()-INTERVAL'1 day'),
  ('Delia',   16, 2,'dificil',  'Delia',    NOW()-INTERVAL'4 days'),
  ('Delia',   14, 3,'normal',   'Delia',    NOW()-INTERVAL'2 days'),
  ('Delia',   19, 0,'facil',    'Delia',    NOW()),
  ('Erreka',  12, 4,'normal',   'Erreka',   NOW()-INTERVAL'5 days'),
  ('Erreka',   6,11,'infernal', 'Erreka',   NOW()-INTERVAL'3 days'),
  ('Erreka',  13, 5,'dificil',  'Erreka',   NOW()-INTERVAL'1 day'),
  ('Flora',   14, 2,'normal',   'Flora',    NOW()-INTERVAL'4 days'),
  ('Flora',   17, 2,'facil',    'Flora',    NOW()-INTERVAL'2 days'),
  ('Flora',   10, 7,'dificil',  'Flora',    NOW()),
  ('Fuchsia', 16, 3,'dificil',  'Fuchsia',  NOW()-INTERVAL'5 days'),
  ('Fuchsia', 15, 2,'normal',   'Fuchsia',  NOW()-INTERVAL'3 days'),
  ('Fuchsia',  8, 9,'infernal', 'Fuchsia',  NOW()-INTERVAL'1 day'),
  ('Giselle', 14, 3,'normal',   'Giselle',  NOW()-INTERVAL'4 days'),
  ('Giselle', 12, 5,'dificil',  'Giselle',  NOW()-INTERVAL'2 days'),
  ('Giselle', 18, 1,'facil',    'Giselle',  NOW()),
  ('Grant',   13, 4,'normal',   'Grant',    NOW()-INTERVAL'5 days'),
  ('Grant',    6,11,'infernal', 'Grant',    NOW()-INTERVAL'3 days'),
  ('Grant',   12, 5,'dificil',  'Grant',    NOW()-INTERVAL'1 day'),
  ('Harlene', 17, 2,'dificil',  'Harlene',  NOW()-INTERVAL'4 days'),
  ('Harlene',  9, 8,'infernal', 'Harlene',  NOW()-INTERVAL'2 days'),
  ('Harlene', 15, 2,'normal',   'Harlene',  NOW()),
  ('Iris',    15, 2,'normal',   'Iris',     NOW()-INTERVAL'5 days'),
  ('Iris',    18, 1,'facil',    'Iris',     NOW()-INTERVAL'3 days'),
  ('Iris',    12, 5,'dificil',  'Iris',     NOW()-INTERVAL'1 day'),
  ('Irina',   14, 2,'normal',   'Irina',    NOW()-INTERVAL'4 days'),
  ('Irina',   11, 6,'dificil',  'Irina',    NOW()-INTERVAL'2 days'),
  ('Irina',   18, 1,'facil',    'Irina',    NOW()),
  ('Jackie',  16, 2,'dificil',  'Jackie',   NOW()-INTERVAL'5 days'),
  ('Jackie',  14, 3,'normal',   'Jackie',   NOW()-INTERVAL'3 days'),
  ('Jackie',  19, 0,'facil',    'Jackie',   NOW()-INTERVAL'1 day'),
  ('Jasmine', 12, 4,'normal',   'Jasmine',  NOW()-INTERVAL'4 days'),
  ('Jasmine', 17, 2,'facil',    'Jasmine',  NOW()-INTERVAL'2 days'),
  ('Jasmine', 10, 7,'dificil',  'Jasmine',  NOW()),
  ('Juan',    14, 2,'normal',   'Juan',     NOW()-INTERVAL'5 days'),
  ('Juan',    17, 2,'facil',    'Juan',     NOW()-INTERVAL'3 days'),
  ('Juan',    10, 7,'dificil',  'Juan',     NOW()-INTERVAL'1 day'),
  ('Kaida',   16, 3,'dificil',  'Kaida',    NOW()-INTERVAL'4 days'),
  ('Kaida',   15, 2,'normal',   'Kaida',    NOW()-INTERVAL'2 days'),
  ('Kaida',    8, 9,'infernal', 'Kaida',    NOW()),
  ('Klara',   17, 2,'dificil',  'Klara',    NOW()-INTERVAL'5 days'),
  ('Klara',    9, 8,'infernal', 'Klara',    NOW()-INTERVAL'3 days'),
  ('Klara',   15, 2,'normal',   'Klara',    NOW()-INTERVAL'1 day')
) AS r(username, captured_count, escaped_count, difficulty_id, explorer_name, completed_at)
ON u.username = r.username;

-- ============================================================================
-- 5. REFRESH TOKENS (uno por usuario, generados automáticamente)
-- ============================================================================

INSERT INTO refresh_tokens (user_id, token, expires_at, created_at)
SELECT u.id, 'refresh_' || lower(u.username) || '_seed_1', NOW() + INTERVAL '7 days', NOW()
FROM users u;

-- ============================================================================
-- 6. REPLAYS (usando subquery para slot_id)
-- ============================================================================

INSERT INTO game_replay (slot_id, user_id, movements, completed_at)
SELECT gs.id, u.id,
  '[{"hp":10,"r":0,"c":0,"pok":0},{"hp":10,"r":1,"c":0,"pok":0},{"hp":10,"r":2,"c":0,"pok":1},{"hp":9,"r":3,"c":1,"pok":1},{"hp":9,"r":4,"c":1,"pok":2}]'::json,
  NOW() - INTERVAL '1 hour'
FROM users u JOIN game_slots gs ON gs.user_id = u.id AND gs.slot_number = 1
WHERE u.username IN ('Luis','Jorge','Ash','Misty','Brock');

-- ============================================================================
-- FIN DEL SEED DATA
-- 47 usuarios | 141 slots | ~200 pokémon capturados | 143 entradas ranking
-- Contraseña de todos: testpass123
-- ============================================================================